name: Maven CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Maven Build 
    uses: jetty-project/.github/.github/workflows/maven-ci.yml@master
    with:
      jdk-matrix: '[ "11" ]'    
      maven_version: "3.8.5"
